version: '{build}'
skip_tags: true
image: Visual Studio 2022
build_script:
    - pwsh: |
        Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
        ./dotnet-install.ps1 -JsonFile global.json -Architecture x64 -InstallDir 'C:\Program Files\dotnet'
        ./Build.ps1
artifacts:
    - path: artifacts/Serilog.*.nupkg
deploy:
    - provider: NuGet
      api_key:
          secure: sDnchSg4TZIOK7oIUI6BJwFPNENTOZrGNsroGO1hehLJSvlHpFmpTwiX8+bgPD+Q
      skip_symbols: true
      on:
          branch: /^(main|dev)$/
    - provider: GitHub
      auth_token:
          secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
      artifact: /Serilog.*\.nupkg/
      tag: v$(appveyor_build_version)
      on:
          branch: main
          
